# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yunzhi/Workshop/smartcube

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yunzhi/Workshop/smartcube

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yunzhi/Workshop/smartcube/CMakeFiles /Users/yunzhi/Workshop/smartcube/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yunzhi/Workshop/smartcube/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xcommon

# Build rule for target.
xcommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcommon
.PHONY : xcommon

# fast build rule for target.
xcommon/fast:
	$(MAKE) -f src/common/CMakeFiles/xcommon.dir/build.make src/common/CMakeFiles/xcommon.dir/build
.PHONY : xcommon/fast

#=============================================================================
# Target rules for targets named xagg.count

# Build rule for target.
xagg.count: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xagg.count
.PHONY : xagg.count

# fast build rule for target.
xagg.count/fast:
	$(MAKE) -f src/aggregate/CMakeFiles/xagg.count.dir/build.make src/aggregate/CMakeFiles/xagg.count.dir/build
.PHONY : xagg.count/fast

#=============================================================================
# Target rules for targets named xagg.head

# Build rule for target.
xagg.head: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xagg.head
.PHONY : xagg.head

# fast build rule for target.
xagg.head/fast:
	$(MAKE) -f src/aggregate/CMakeFiles/xagg.head.dir/build.make src/aggregate/CMakeFiles/xagg.head.dir/build
.PHONY : xagg.head/fast

#=============================================================================
# Target rules for targets named xagg.sum

# Build rule for target.
xagg.sum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xagg.sum
.PHONY : xagg.sum

# fast build rule for target.
xagg.sum/fast:
	$(MAKE) -f src/aggregate/CMakeFiles/xagg.sum.dir/build.make src/aggregate/CMakeFiles/xagg.sum.dir/build
.PHONY : xagg.sum/fast

#=============================================================================
# Target rules for targets named xagg.tail

# Build rule for target.
xagg.tail: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xagg.tail
.PHONY : xagg.tail

# fast build rule for target.
xagg.tail/fast:
	$(MAKE) -f src/aggregate/CMakeFiles/xagg.tail.dir/build.make src/aggregate/CMakeFiles/xagg.tail.dir/build
.PHONY : xagg.tail/fast

#=============================================================================
# Target rules for targets named xbit.and

# Build rule for target.
xbit.and: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xbit.and
.PHONY : xbit.and

# fast build rule for target.
xbit.and/fast:
	$(MAKE) -f src/bitwise/CMakeFiles/xbit.and.dir/build.make src/bitwise/CMakeFiles/xbit.and.dir/build
.PHONY : xbit.and/fast

#=============================================================================
# Target rules for targets named xbit.not

# Build rule for target.
xbit.not: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xbit.not
.PHONY : xbit.not

# fast build rule for target.
xbit.not/fast:
	$(MAKE) -f src/bitwise/CMakeFiles/xbit.not.dir/build.make src/bitwise/CMakeFiles/xbit.not.dir/build
.PHONY : xbit.not/fast

#=============================================================================
# Target rules for targets named xbit.or

# Build rule for target.
xbit.or: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xbit.or
.PHONY : xbit.or

# fast build rule for target.
xbit.or/fast:
	$(MAKE) -f src/bitwise/CMakeFiles/xbit.or.dir/build.make src/bitwise/CMakeFiles/xbit.or.dir/build
.PHONY : xbit.or/fast

#=============================================================================
# Target rules for targets named xbit.xor

# Build rule for target.
xbit.xor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xbit.xor
.PHONY : xbit.xor

# fast build rule for target.
xbit.xor/fast:
	$(MAKE) -f src/bitwise/CMakeFiles/xbit.xor.dir/build.make src/bitwise/CMakeFiles/xbit.xor.dir/build
.PHONY : xbit.xor/fast

#=============================================================================
# Target rules for targets named xcls.backfill

# Build rule for target.
xcls.backfill: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcls.backfill
.PHONY : xcls.backfill

# fast build rule for target.
xcls.backfill/fast:
	$(MAKE) -f src/cleansing/CMakeFiles/xcls.backfill.dir/build.make src/cleansing/CMakeFiles/xcls.backfill.dir/build
.PHONY : xcls.backfill/fast

#=============================================================================
# Target rules for targets named xcol.combine

# Build rule for target.
xcol.combine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcol.combine
.PHONY : xcol.combine

# fast build rule for target.
xcol.combine/fast:
	$(MAKE) -f src/column/CMakeFiles/xcol.combine.dir/build.make src/column/CMakeFiles/xcol.combine.dir/build
.PHONY : xcol.combine/fast

#=============================================================================
# Target rules for targets named xcol.expand

# Build rule for target.
xcol.expand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcol.expand
.PHONY : xcol.expand

# fast build rule for target.
xcol.expand/fast:
	$(MAKE) -f src/column/CMakeFiles/xcol.expand.dir/build.make src/column/CMakeFiles/xcol.expand.dir/build
.PHONY : xcol.expand/fast

#=============================================================================
# Target rules for targets named xcol.select

# Build rule for target.
xcol.select: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcol.select
.PHONY : xcol.select

# fast build rule for target.
xcol.select/fast:
	$(MAKE) -f src/column/CMakeFiles/xcol.select.dir/build.make src/column/CMakeFiles/xcol.select.dir/build
.PHONY : xcol.select/fast

#=============================================================================
# Target rules for targets named xcol.split

# Build rule for target.
xcol.split: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcol.split
.PHONY : xcol.split

# fast build rule for target.
xcol.split/fast:
	$(MAKE) -f src/column/CMakeFiles/xcol.split.dir/build.make src/column/CMakeFiles/xcol.split.dir/build
.PHONY : xcol.split/fast

#=============================================================================
# Target rules for targets named xcol.xsplit

# Build rule for target.
xcol.xsplit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xcol.xsplit
.PHONY : xcol.xsplit

# fast build rule for target.
xcol.xsplit/fast:
	$(MAKE) -f src/column/CMakeFiles/xcol.xsplit.dir/build.make src/column/CMakeFiles/xcol.xsplit.dir/build
.PHONY : xcol.xsplit/fast

#=============================================================================
# Target rules for targets named xenc.b64dec

# Build rule for target.
xenc.b64dec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xenc.b64dec
.PHONY : xenc.b64dec

# fast build rule for target.
xenc.b64dec/fast:
	$(MAKE) -f src/encode/CMakeFiles/xenc.b64dec.dir/build.make src/encode/CMakeFiles/xenc.b64dec.dir/build
.PHONY : xenc.b64dec/fast

#=============================================================================
# Target rules for targets named xenc.b64enc

# Build rule for target.
xenc.b64enc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xenc.b64enc
.PHONY : xenc.b64enc

# fast build rule for target.
xenc.b64enc/fast:
	$(MAKE) -f src/encode/CMakeFiles/xenc.b64enc.dir/build.make src/encode/CMakeFiles/xenc.b64enc.dir/build
.PHONY : xenc.b64enc/fast

#=============================================================================
# Target rules for targets named xenc.hexdec

# Build rule for target.
xenc.hexdec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xenc.hexdec
.PHONY : xenc.hexdec

# fast build rule for target.
xenc.hexdec/fast:
	$(MAKE) -f src/encode/CMakeFiles/xenc.hexdec.dir/build.make src/encode/CMakeFiles/xenc.hexdec.dir/build
.PHONY : xenc.hexdec/fast

#=============================================================================
# Target rules for targets named xenc.hexenc

# Build rule for target.
xenc.hexenc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xenc.hexenc
.PHONY : xenc.hexenc

# fast build rule for target.
xenc.hexenc/fast:
	$(MAKE) -f src/encode/CMakeFiles/xenc.hexenc.dir/build.make src/encode/CMakeFiles/xenc.hexenc.dir/build
.PHONY : xenc.hexenc/fast

#=============================================================================
# Target rules for targets named xgrp.group

# Build rule for target.
xgrp.group: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xgrp.group
.PHONY : xgrp.group

# fast build rule for target.
xgrp.group/fast:
	$(MAKE) -f src/group/CMakeFiles/xgrp.group.dir/build.make src/group/CMakeFiles/xgrp.group.dir/build
.PHONY : xgrp.group/fast

#=============================================================================
# Target rules for targets named xgrp.ungroup

# Build rule for target.
xgrp.ungroup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xgrp.ungroup
.PHONY : xgrp.ungroup

# fast build rule for target.
xgrp.ungroup/fast:
	$(MAKE) -f src/group/CMakeFiles/xgrp.ungroup.dir/build.make src/group/CMakeFiles/xgrp.ungroup.dir/build
.PHONY : xgrp.ungroup/fast

#=============================================================================
# Target rules for targets named xlog.and

# Build rule for target.
xlog.and: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.and
.PHONY : xlog.and

# fast build rule for target.
xlog.and/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.and.dir/build.make src/logic/CMakeFiles/xlog.and.dir/build
.PHONY : xlog.and/fast

#=============================================================================
# Target rules for targets named xlog.cmp

# Build rule for target.
xlog.cmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.cmp
.PHONY : xlog.cmp

# fast build rule for target.
xlog.cmp/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.cmp.dir/build.make src/logic/CMakeFiles/xlog.cmp.dir/build
.PHONY : xlog.cmp/fast

#=============================================================================
# Target rules for targets named xlog.eq

# Build rule for target.
xlog.eq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.eq
.PHONY : xlog.eq

# fast build rule for target.
xlog.eq/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.eq.dir/build.make src/logic/CMakeFiles/xlog.eq.dir/build
.PHONY : xlog.eq/fast

#=============================================================================
# Target rules for targets named xlog.ge

# Build rule for target.
xlog.ge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.ge
.PHONY : xlog.ge

# fast build rule for target.
xlog.ge/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.ge.dir/build.make src/logic/CMakeFiles/xlog.ge.dir/build
.PHONY : xlog.ge/fast

#=============================================================================
# Target rules for targets named xlog.gt

# Build rule for target.
xlog.gt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.gt
.PHONY : xlog.gt

# fast build rule for target.
xlog.gt/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.gt.dir/build.make src/logic/CMakeFiles/xlog.gt.dir/build
.PHONY : xlog.gt/fast

#=============================================================================
# Target rules for targets named xlog.le

# Build rule for target.
xlog.le: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.le
.PHONY : xlog.le

# fast build rule for target.
xlog.le/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.le.dir/build.make src/logic/CMakeFiles/xlog.le.dir/build
.PHONY : xlog.le/fast

#=============================================================================
# Target rules for targets named xlog.lt

# Build rule for target.
xlog.lt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.lt
.PHONY : xlog.lt

# fast build rule for target.
xlog.lt/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.lt.dir/build.make src/logic/CMakeFiles/xlog.lt.dir/build
.PHONY : xlog.lt/fast

#=============================================================================
# Target rules for targets named xlog.ne

# Build rule for target.
xlog.ne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.ne
.PHONY : xlog.ne

# fast build rule for target.
xlog.ne/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.ne.dir/build.make src/logic/CMakeFiles/xlog.ne.dir/build
.PHONY : xlog.ne/fast

#=============================================================================
# Target rules for targets named xlog.not

# Build rule for target.
xlog.not: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.not
.PHONY : xlog.not

# fast build rule for target.
xlog.not/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.not.dir/build.make src/logic/CMakeFiles/xlog.not.dir/build
.PHONY : xlog.not/fast

#=============================================================================
# Target rules for targets named xlog.or

# Build rule for target.
xlog.or: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.or
.PHONY : xlog.or

# fast build rule for target.
xlog.or/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.or.dir/build.make src/logic/CMakeFiles/xlog.or.dir/build
.PHONY : xlog.or/fast

#=============================================================================
# Target rules for targets named xlog.xor

# Build rule for target.
xlog.xor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlog.xor
.PHONY : xlog.xor

# fast build rule for target.
xlog.xor/fast:
	$(MAKE) -f src/logic/CMakeFiles/xlog.xor.dir/build.make src/logic/CMakeFiles/xlog.xor.dir/build
.PHONY : xlog.xor/fast

#=============================================================================
# Target rules for targets named xmath.add

# Build rule for target.
xmath.add: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.add
.PHONY : xmath.add

# fast build rule for target.
xmath.add/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.add.dir/build.make src/math/CMakeFiles/xmath.add.dir/build
.PHONY : xmath.add/fast

#=============================================================================
# Target rules for targets named xmath.ceil

# Build rule for target.
xmath.ceil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.ceil
.PHONY : xmath.ceil

# fast build rule for target.
xmath.ceil/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.ceil.dir/build.make src/math/CMakeFiles/xmath.ceil.dir/build
.PHONY : xmath.ceil/fast

#=============================================================================
# Target rules for targets named xmath.div

# Build rule for target.
xmath.div: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.div
.PHONY : xmath.div

# fast build rule for target.
xmath.div/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.div.dir/build.make src/math/CMakeFiles/xmath.div.dir/build
.PHONY : xmath.div/fast

#=============================================================================
# Target rules for targets named xmath.exp

# Build rule for target.
xmath.exp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.exp
.PHONY : xmath.exp

# fast build rule for target.
xmath.exp/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.exp.dir/build.make src/math/CMakeFiles/xmath.exp.dir/build
.PHONY : xmath.exp/fast

#=============================================================================
# Target rules for targets named xmath.floor

# Build rule for target.
xmath.floor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.floor
.PHONY : xmath.floor

# fast build rule for target.
xmath.floor/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.floor.dir/build.make src/math/CMakeFiles/xmath.floor.dir/build
.PHONY : xmath.floor/fast

#=============================================================================
# Target rules for targets named xmath.log

# Build rule for target.
xmath.log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.log
.PHONY : xmath.log

# fast build rule for target.
xmath.log/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.log.dir/build.make src/math/CMakeFiles/xmath.log.dir/build
.PHONY : xmath.log/fast

#=============================================================================
# Target rules for targets named xmath.mul

# Build rule for target.
xmath.mul: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.mul
.PHONY : xmath.mul

# fast build rule for target.
xmath.mul/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.mul.dir/build.make src/math/CMakeFiles/xmath.mul.dir/build
.PHONY : xmath.mul/fast

#=============================================================================
# Target rules for targets named xmath.round

# Build rule for target.
xmath.round: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.round
.PHONY : xmath.round

# fast build rule for target.
xmath.round/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.round.dir/build.make src/math/CMakeFiles/xmath.round.dir/build
.PHONY : xmath.round/fast

#=============================================================================
# Target rules for targets named xmath.sub

# Build rule for target.
xmath.sub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmath.sub
.PHONY : xmath.sub

# fast build rule for target.
xmath.sub/fast:
	$(MAKE) -f src/math/CMakeFiles/xmath.sub.dir/build.make src/math/CMakeFiles/xmath.sub.dir/build
.PHONY : xmath.sub/fast

#=============================================================================
# Target rules for targets named xnorm

# Build rule for target.
xnorm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xnorm
.PHONY : xnorm

# fast build rule for target.
xnorm/fast:
	$(MAKE) -f src/misc/CMakeFiles/xnorm.dir/build.make src/misc/CMakeFiles/xnorm.dir/build
.PHONY : xnorm/fast

#=============================================================================
# Target rules for targets named xrow.filter

# Build rule for target.
xrow.filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xrow.filter
.PHONY : xrow.filter

# fast build rule for target.
xrow.filter/fast:
	$(MAKE) -f src/row/CMakeFiles/xrow.filter.dir/build.make src/row/CMakeFiles/xrow.filter.dir/build
.PHONY : xrow.filter/fast

#=============================================================================
# Target rules for targets named xstr.len

# Build rule for target.
xstr.len: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstr.len
.PHONY : xstr.len

# fast build rule for target.
xstr.len/fast:
	$(MAKE) -f src/string/CMakeFiles/xstr.len.dir/build.make src/string/CMakeFiles/xstr.len.dir/build
.PHONY : xstr.len/fast

#=============================================================================
# Target rules for targets named xstr.strip

# Build rule for target.
xstr.strip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstr.strip
.PHONY : xstr.strip

# fast build rule for target.
xstr.strip/fast:
	$(MAKE) -f src/string/CMakeFiles/xstr.strip.dir/build.make src/string/CMakeFiles/xstr.strip.dir/build
.PHONY : xstr.strip/fast

#=============================================================================
# Target rules for targets named xstr.substr

# Build rule for target.
xstr.substr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstr.substr
.PHONY : xstr.substr

# fast build rule for target.
xstr.substr/fast:
	$(MAKE) -f src/string/CMakeFiles/xstr.substr.dir/build.make src/string/CMakeFiles/xstr.substr.dir/build
.PHONY : xstr.substr/fast

#=============================================================================
# Target rules for targets named xstr.xformat

# Build rule for target.
xstr.xformat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstr.xformat
.PHONY : xstr.xformat

# fast build rule for target.
xstr.xformat/fast:
	$(MAKE) -f src/string/CMakeFiles/xstr.xformat.dir/build.make src/string/CMakeFiles/xstr.xformat.dir/build
.PHONY : xstr.xformat/fast

#=============================================================================
# Target rules for targets named xstr.xreplace

# Build rule for target.
xstr.xreplace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstr.xreplace
.PHONY : xstr.xreplace

# fast build rule for target.
xstr.xreplace/fast:
	$(MAKE) -f src/string/CMakeFiles/xstr.xreplace.dir/build.make src/string/CMakeFiles/xstr.xreplace.dir/build
.PHONY : xstr.xreplace/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xcommon"
	@echo "... xagg.count"
	@echo "... xagg.head"
	@echo "... xagg.sum"
	@echo "... xagg.tail"
	@echo "... xbit.and"
	@echo "... xbit.not"
	@echo "... xbit.or"
	@echo "... xbit.xor"
	@echo "... xcls.backfill"
	@echo "... xcol.combine"
	@echo "... xcol.expand"
	@echo "... xcol.select"
	@echo "... xcol.split"
	@echo "... xcol.xsplit"
	@echo "... xenc.b64dec"
	@echo "... xenc.b64enc"
	@echo "... xenc.hexdec"
	@echo "... xenc.hexenc"
	@echo "... xgrp.group"
	@echo "... xgrp.ungroup"
	@echo "... xlog.and"
	@echo "... xlog.cmp"
	@echo "... xlog.eq"
	@echo "... xlog.ge"
	@echo "... xlog.gt"
	@echo "... xlog.le"
	@echo "... xlog.lt"
	@echo "... xlog.ne"
	@echo "... xlog.not"
	@echo "... xlog.or"
	@echo "... xlog.xor"
	@echo "... xmath.add"
	@echo "... xmath.ceil"
	@echo "... xmath.div"
	@echo "... xmath.exp"
	@echo "... xmath.floor"
	@echo "... xmath.log"
	@echo "... xmath.mul"
	@echo "... xmath.round"
	@echo "... xmath.sub"
	@echo "... xnorm"
	@echo "... xrow.filter"
	@echo "... xstr.len"
	@echo "... xstr.strip"
	@echo "... xstr.substr"
	@echo "... xstr.xformat"
	@echo "... xstr.xreplace"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

